apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-cd-sealed-secret-role-binding
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
roleRef:
  kind: Role
  name: sealed-secrets-management
  apiGroup: rbac.authorization.k8s.io
