kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealed-secrets-management
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
rules:
- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets"]
  verbs: ["get", "patch", "delete", "create"]
